apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: awareness
  name: web-deployment
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - image: gcr.io/sec-production/awareness-web:latest
          imagePullPolicy: Always
          name: web
          env:
            - name: PORT
              value: "3000"
            - name: PROXY
              value: http://api:8080/
          ports:
            - containerPort: 3000
              name: web
