apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: awareness
  name: admin-deployment
  labels:
    app: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - image: gcr.io/sec-production/awareness-admin:latest
          imagePullPolicy: Always
          name: admin
          env:
            - name: PORT
              value: "3000"
            - name: PROXY
              value: http://api:8080/
          ports:
            - containerPort: 3000
              name: admin
