name: Deploy API

on: workflow_dispatch

jobs:
  api:
    name: API
    uses: AbdallahMostafaIbrahim/turbo-learn/.github/workflows/generic-deploy.yml@main
    with:
      folder: ./apps/api
      cluster: security-meter
      zone: europe-central2-a
      dockerfile: ./deployment/docker/api.DockerFile
      dockertag: "gcr.io/sec-production/awareness-api"
      deployment: api-deployment
      namespace: awareness
    secrets:
      google_credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
