name: Deploy Admin

on: workflow_dispatch

jobs:
  admin:
    name: Admin
    uses: AbdallahMostafaIbrahim/awareness/.github/workflows/generic-deploy.yml@main
    with:
      folder: ./apps/admin
      cluster: security-meter
      zone: europe-central2-a
      dockerfile: ./deployment/docker/admin.DockerFile
      dockertag: "gcr.io/sec-production/awareness-admin"
      deployment: admin-deployment
      namespace: awareness
    secrets:
      google_credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
