name: Deploy Web

on: workflow_dispatch

jobs:
  web:
    name: Web
    uses: AbdallahMostafaIbrahim/turbo-learn/.github/workflows/generic-deploy.yml@main
    with:
      folder: ./apps/web
      cluster: security-meter
      zone: europe-central2-a
      dockerfile: ./deployment/docker/web.DockerFile
      dockertag: "gcr.io/sec-production/awareness-web"
      deployment: web-deployment
      namespace: awareness
    secrets:
      google_credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
